CREATE DATABASE IF NOT EXISTS CUSTOMER360_HACKATHON;
CREATE SCHEMA IF NOT EXISTS CUSTOMER360_HACKATHON.APP;

USE DATABASE CUSTOMER360_HACKATHON;
USE SCHEMA APP;

CREATE TABLE IF NOT EXISTS CUSTOMERS (
  CUSTOMER_ID STRING,
  NAME STRING,
  SEGMENT STRING,
  CITY STRING,
  INDUSTRY STRING,
  TENURE_YEARS NUMBER(5, 2),
  PRODUCT_COUNT NUMBER,
  ANNUAL_VALUE NUMBER
);

CREATE TABLE IF NOT EXISTS ACCOUNTS (
  ACCOUNT_ID STRING,
  CUSTOMER_ID STRING,
  PRODUCT_TYPE STRING,
  STATUS STRING,
  BALANCE_OR_COVER NUMBER,
  OPENED_DATE DATE
);

CREATE TABLE IF NOT EXISTS INTERACTIONS (
  INTERACTION_ID STRING,
  CUSTOMER_ID STRING,
  CHANNEL STRING,
  INTERACTION_DATE DATE,
  ISSUE_TYPE STRING,
  SENTIMENT STRING,
  STATUS STRING,
  TRANSCRIPT STRING
);
