USE DATABASE CUSTOMER360_HACKATHON;
USE SCHEMA APP;

CREATE OR REPLACE VIEW CUSTOMER_360 AS
WITH interaction_rollup AS (
  SELECT
    CUSTOMER_ID,
    COUNT(*) AS INTERACTION_COUNT,
    COUNT_IF(STATUS = 'Open') AS OPEN_CASES,
    COUNT_IF(SENTIMENT = 'Negative') AS NEGATIVE_INTERACTIONS,
    MAX(INTERACTION_DATE) AS LAST_INTERACTION_DATE
  FROM INTERACTIONS
  GROUP BY CUSTOMER_ID
),
account_rollup AS (
  SELECT
    CUSTOMER_ID,
    COUNT(*) AS ACCOUNT_COUNT,
    SUM(BALANCE_OR_COVER) AS TOTAL_BALANCE_OR_COVER
  FROM ACCOUNTS
  GROUP BY CUSTOMER_ID
)
SELECT
  c.CUSTOMER_ID,
  c.NAME,
  c.SEGMENT,
  c.CITY,
  c.INDUSTRY,
  c.TENURE_YEARS,
  c.PRODUCT_COUNT,
  c.ANNUAL_VALUE,
  COALESCE(a.ACCOUNT_COUNT, 0) AS ACCOUNT_COUNT,
  COALESCE(a.TOTAL_BALANCE_OR_COVER, 0) AS TOTAL_BALANCE_OR_COVER,
  COALESCE(i.INTERACTION_COUNT, 0) AS INTERACTION_COUNT,
  COALESCE(i.OPEN_CASES, 0) AS OPEN_CASES,
  COALESCE(i.NEGATIVE_INTERACTIONS, 0) AS NEGATIVE_INTERACTIONS,
  i.LAST_INTERACTION_DATE
FROM CUSTOMERS c
LEFT JOIN account_rollup a ON c.CUSTOMER_ID = a.CUSTOMER_ID
LEFT JOIN interaction_rollup i ON c.CUSTOMER_ID = i.CUSTOMER_ID;
