USE DATABASE CUSTOMER360_HACKATHON;
USE SCHEMA APP;

CREATE OR REPLACE TAG DATA_CLASSIFICATION
  ALLOWED_VALUES 'PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'SENSITIVE';

ALTER TABLE CUSTOMERS SET TAG DATA_CLASSIFICATION = 'CONFIDENTIAL';
ALTER TABLE INTERACTIONS SET TAG DATA_CLASSIFICATION = 'SENSITIVE';

CREATE OR REPLACE MASKING POLICY CUSTOMER_NAME_MASK AS (val STRING)
  RETURNS STRING ->
    CASE
      WHEN CURRENT_ROLE() IN ('CUSTOMER360_ADMIN', 'CUSTOMER360_AGENT') THEN val
      ELSE 'MASKED_CUSTOMER'
    END;

ALTER TABLE CUSTOMERS
  MODIFY COLUMN NAME SET MASKING POLICY CUSTOMER_NAME_MASK;

CREATE OR REPLACE VIEW CUSTOMER_360_SEMANTIC_BASE AS
SELECT
  CUSTOMER_ID,
  NAME,
  SEGMENT,
  CITY,
  INDUSTRY,
  TENURE_YEARS,
  PRODUCT_COUNT,
  ANNUAL_VALUE,
  ACCOUNT_COUNT,
  TOTAL_BALANCE_OR_COVER,
  INTERACTION_COUNT,
  OPEN_CASES,
  NEGATIVE_INTERACTIONS,
  LAST_INTERACTION_DATE
FROM CUSTOMER_360;

-- Use this view as the governed business layer for Cortex Analyst or semantic views.
-- Example trusted questions:
-- 1. Which premium customers have open cases and negative sentiment?
-- 2. What is the total annual value exposed to high service risk?
-- 3. Which regions have the highest concentration of unresolved customer issues?
