USE DATABASE CUSTOMER360_HACKATHON;
USE SCHEMA APP;

CREATE TABLE IF NOT EXISTS RECOMMENDATION_EVENTS (
  EVENT_ID STRING,
  CUSTOMER_ID STRING,
  RECOMMENDED_ACTION STRING,
  ACTION_OWNER STRING,
  RISK_SCORE NUMBER,
  PRIORITY_TIER STRING,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  ACCEPTED BOOLEAN,
  OUTCOME STRING,
  OUTCOME_NOTES STRING
);

CREATE OR REPLACE VIEW RECOMMENDATION_EFFECTIVENESS AS
SELECT
  RECOMMENDED_ACTION,
  COUNT(*) AS RECOMMENDATION_COUNT,
  COUNT_IF(ACCEPTED) AS ACCEPTED_COUNT,
  ROUND(COUNT_IF(ACCEPTED) / NULLIF(COUNT(*), 0), 2) AS ACCEPTANCE_RATE,
  COUNT_IF(OUTCOME = 'Resolved') AS RESOLVED_COUNT,
  COUNT_IF(OUTCOME = 'Churn Prevented') AS CHURN_PREVENTED_COUNT
FROM RECOMMENDATION_EVENTS
GROUP BY RECOMMENDED_ACTION;

-- Proposed monitoring schema. Populate only from verified human-reported outcomes;
-- do not treat association as causal evidence of churn prevention.
